/*
 * This script implements Bitcoin lock validation in ckb.
 *
 * How to verify Bitcoin lock?
 *
 * We know that the format of the Bitcoin address is
 * base58(version + ripemd160(sha256(pubkey)) + sha256(sha256(version + ripemd160(sha256(pubkey))))[0..4])
 *
 * So by verifying the hash of ripemd160(sha256(pubkey)) and verifying the ownership of the pubkey,
 * you can achieve the purpose of verifying the ownership of the private key.
 *
 * How to use this script?
 *
 * We need verify ripemd160(sha256(pubkey)), so transaction lock script like this:
 *
 * ```
 * dependence_code_hash = "this script binary hash"
 * args = [ "ripemd160(sha256(pubkey))" ]
 * ```
 *
 * We need verify the ownership of the pubkey, so transaction witness is:
 *
 * witness = [signature, pubkey]
 *
 * Signature generated by your private key sign transaction hash
 */
#include "ckb_syscalls.h"
#include "protocol.h"
#include "ripemd160.h"
#include "secp256k1_helper.h"
#include "sha256.h"

#define ERROR_UNKNOWN -1
#define ERROR_WRONG_NUMBER_OF_ARGUMENTS -2
#define ERROR_PUBKEY_RIPEMD160_HASH -3
#define ERROR_SYSCALL -4
#define ERROR_SECP_ABORT -5
#define ERROR_SECP_INITIALIZE -6
#define ERROR_SECP_PARSE_PUBKEY -7
#define ERROR_SECP_PARSE_SIGNATURE -8
#define ERROR_SECP_VERIFICATION -9
#define ERROR_BUFFER_NOT_ENOUGH -10
#define ERROR_ENCODING -11
#define ERROR_WITNESS_SIZE -12

#define BLAKE2B_BLOCK_SIZE 32
#define RIPEMD160_SIZE 20
#define SHA256_SIZE 32
#define TEMP_SIZE 1024
#define RECID_INDEX 64
/* 32 KB */
#define WITNESS_SIZE 32768
#define SCRIPT_SIZE 32768
#define RECOVERABLE_SIGNATURE_SIZE 65
#define NONE_RECOVERABLE_SIGNATURE_SIZE 64
#define COMPRESSED_PUBKEY_SIZE 33
#define NONE_COMPRESSED_PUBKEY_SIZE 65

/*
 * Arguments are listed in the following order:
 * 0. ripemd160(sha256(pubkey)) hash, used to
 * shield the real pubkey in lock script.
 *
 * Witness:
 * 0. signature, signature used to present ownership
 * 1. pubkey, real pubkey used to identify token owner
 */
int main() {
  int ret;
  size_t index = 0;
  uint64_t len = 0;
  unsigned char tx_hash[BLAKE2B_BLOCK_SIZE];
  unsigned char temp[TEMP_SIZE];
  unsigned char witness[WITNESS_SIZE];
  unsigned char script[SCRIPT_SIZE];
  uint8_t secp_data[CKB_SECP256K1_DATA_SIZE];
  mol_seg_t script_seg;
  mol_seg_t args_seg;
  mol_seg_t bytes_seg;

  /* Load args */
  len = SCRIPT_SIZE;
  ret = ckb_load_script(script, &len, 0);
  if (ret != CKB_SUCCESS) {
    return ERROR_SYSCALL;
  }
  script_seg.ptr = (uint8_t*)script;
  script_seg.size = len;
  if (MolReader_Script_verify(&script_seg, false) != MOL_OK) {
    return ERROR_ENCODING;
  }
  args_seg = MolReader_Script_get_args(&script_seg);
  bytes_seg = MolReader_Bytes_raw_bytes(&args_seg);
  if (bytes_seg.size != RIPEMD160_SIZE) {
    return ERROR_WRONG_NUMBER_OF_ARGUMENTS;
  }

  secp256k1_context context;
  ret = ckb_secp256k1_custom_verify_only_initialize(&context, secp_data);
  if (ret != 0) {
    return ret;
  }

  len = BLAKE2B_BLOCK_SIZE;
  ret = ckb_load_tx_hash(tx_hash, &len, 0);
  if (ret != CKB_SUCCESS) {
    return ERROR_SYSCALL;
  }

  while (1) {
    len = 0;
    /*
     * Actually we don't need this syscall, we are just making it to grab all
     * input indices for current group, from which we can load the actual
     * witness data we need. `since` field is chosen here since it has a fixed
     * size of 8 bytes, which is both predictable, and also provides minimal
     * cycle consumption.
     */
    ret = ckb_load_input_by_field(NULL, &len, 0, index, CKB_SOURCE_GROUP_INPUT,
                                  CKB_INPUT_FIELD_SINCE);
    if (ret == CKB_INDEX_OUT_OF_BOUND) {
      return 0;
    }
    if (ret != CKB_SUCCESS) {
      return ERROR_SYSCALL;
    }

    /* Now we load actual witness data using the same input index above. */
    len = WITNESS_SIZE;
    ret = ckb_load_witness(witness, &len, 0, index, CKB_SOURCE_GROUP_INPUT);
    if (ret != CKB_SUCCESS) {
      return ERROR_SYSCALL;
    }
    if (len != RECOVERABLE_SIGNATURE_SIZE + NONE_COMPRESSED_PUBKEY_SIZE
        && len != RECOVERABLE_SIGNATURE_SIZE + COMPRESSED_PUBKEY_SIZE
        && len != NONE_RECOVERABLE_SIGNATURE_SIZE + NONE_COMPRESSED_PUBKEY_SIZE
        && len != NONE_RECOVERABLE_SIGNATURE_SIZE + COMPRESSED_PUBKEY_SIZE) {
      return ERROR_WITNESS_SIZE;
    }

    /* parse pubkey */
    secp256k1_pubkey pubkey;
    sha256_state sha256_ctx;
    sha256_init(&sha256_ctx);
    if (len == RECOVERABLE_SIGNATURE_SIZE + NONE_COMPRESSED_PUBKEY_SIZE
      || len == NONE_RECOVERABLE_SIGNATURE_SIZE + NONE_COMPRESSED_PUBKEY_SIZE) {
      if (secp256k1_ec_pubkey_parse(&context, &pubkey, &witness[len - NONE_COMPRESSED_PUBKEY_SIZE],
                  NONE_COMPRESSED_PUBKEY_SIZE) == 0) {
        return ERROR_SECP_PARSE_PUBKEY;
      } else {
        sha256_update(&sha256_ctx, &witness[len - NONE_COMPRESSED_PUBKEY_SIZE], NONE_COMPRESSED_PUBKEY_SIZE);
      }
    } else {
      if (secp256k1_ec_pubkey_parse(&context, &pubkey, &witness[len - COMPRESSED_PUBKEY_SIZE],
                  COMPRESSED_PUBKEY_SIZE) == 0) {
        return ERROR_SECP_PARSE_PUBKEY;
      } else {
        sha256_update(&sha256_ctx, &witness[len - COMPRESSED_PUBKEY_SIZE], COMPRESSED_PUBKEY_SIZE);
      }
    }
    sha256_finalize(&sha256_ctx, temp);

    ripemd160_state ripe160_ctx;
    ripemd160_init(&ripe160_ctx);
    ripemd160_update(&ripe160_ctx, temp, SHA256_SIZE);
    ripemd160_finalize(&ripe160_ctx, temp);

    /* check pubkey hash */
    if (memcmp(bytes_seg.ptr, temp, RIPEMD160_SIZE) != 0) {
      return ERROR_PUBKEY_RIPEMD160_HASH;
    }

    /* Load signature */
    secp256k1_ecdsa_signature signature;
    if (secp256k1_ecdsa_signature_parse_compact(&context, &signature, witness) == 0) {
        return ERROR_SECP_PARSE_SIGNATURE;
    }

    /* verify signature */
    if (secp256k1_ecdsa_verify(&context, &signature, tx_hash, &pubkey) != 1) {
      return ERROR_SECP_VERIFICATION;
    }

    index += 1;
  }
  return ERROR_UNKNOWN;
}
